In [1]:
#
import numpy as np
import pandas as pd

sea_level_data = [1, 2, 3, 4, 5]
sea_level_array = np.array(sea_level_data)
print(sea_level_array)

range_array = np.arange(0, 10, 2)
print(range_array)

evenly_spaced_array = np.linspace(0, 1, 5)
print(evenly_spaced_array)

zeros_array = np.zeros((3, 4))
print(zeros_array)

ones_array = np.ones((2, 3))
print(ones_array)

identity_matrix = np.eye(4)
print(identity_matrix)

random_values_array = np.random.rand(3, 3)
print(random_values_array)

sea_level_data_from_csv = np.genfromtxt('epa-sea-level.csv', delimiter=',', skip_header=1)
print(sea_level_data_from_csv)

one_dimensional_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
reshaped_matrix = one_dimensional_array.reshape((3, 3))
print(reshaped_matrix)

data_frame = pd.read_csv('epa-sea-level.csv')

years = data_frame['Year'].values
sea_levels = data_frame['CSIRO Adjusted Sea Level'].values

average_sea_level = np.mean(sea_levels)
print(f"Average Sea Level: {average_sea_level} inches")

adjusted_sea_levels = sea_levels + 0.2 * (years - 2000)

adjusted_sea_levels_after_2000 = adjusted_sea_levels[years >= 2000]
print("\nAdjusted Sea Levels for years after 2000:")
print(adjusted_sea_levels_after_2000)

[1 2 3 4 5]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.49815528 0.59602445 0.10217617]
 [0.46778558 0.38284694 0.59224803]
 [0.54186109 0.491892   0.18589271]]
[[1.880e+03 1.000e-01]
 [1.881e+03 1.000e-01]
 [1.882e+03 1.000e-01]
 [1.883e+03 1.000e-01]
 [1.884e+03 1.000e-01]
 [1.885e+03 1.000e-01]
 [1.886e+03 1.000e-01]
 [1.887e+03 1.000e-01]
 [1.888e+03 1.000e-01]
 [1.889e+03 1.000e-01]
 [1.890e+03 1.000e-01]
 [1.891e+03 1.000e-01]
 [1.892e+03 1.000e-01]
 [1.893e+03 1.000e-01]
 [1.894e+03 1.000e-01]
 [1.895e+03 1.000e-01]
 [1.896e+03 1.000e-01]
 [1.897e+03 1.000e-01]
 [1.898e+03 1.000e-01]
 [1.899e+03 1.000e-01]
 [1.900e+03 1.000e-01]
 [2.000e+03 4.200e+00]
 [2.001e+03 4.300e+00]
 [2.002e+03 4.500e+00]
 [2.003e+03 4.700e+00]
 [2.004e+03 4.900e+00]
 [2.005e+03 5.000e+00]
 [2.006e+03 5.200e+00]
 [2.007e+03 5.400e+00]
 [2.008e+03 5.600e+00]
 [2.009e+03 5.700e

In [3]:
#
import numpy as np
import pandas as pd

data_frame = pd.read_csv('epa-sea-level.csv')

years = data_frame['Year'].values
sea_levels = data_frame['CSIRO Adjusted Sea Level'].values

adjusted_sea_levels = sea_levels + 0.3 * (years - 2000)

mean_sea_level = np.mean(sea_levels)
sum_sea_level = np.sum(sea_levels)

print(f"Mean Sea Level: {mean_sea_level} inches")
print(f"Sum of Sea Level Data: {sum_sea_level} inches")

recent_years = years[years > 2000]
recent_sea_levels = sea_levels[years > 2000]

combined_data = np.column_stack((years, sea_levels))

combined_adjusted_data = np.column_stack((years, adjusted_sea_levels))

vertical_combined_data = np.vstack((combined_data, combined_adjusted_data))

print("Combined Data (Years and Original Sea Levels):")
print(combined_data)

print("Combined Adjusted Data (Years and Adjusted Sea Levels):")
print(combined_adjusted_data)

print("Vertical Combined Data (Original and Adjusted):")
print(vertical_combined_data)

high_sea_levels_years = years[sea_levels > 7]
high_sea_levels_values = sea_levels[sea_levels > 7]

print("Years with Sea Levels Greater Than 7 Inches:")
print(high_sea_levels_years)
print(high_sea_levels_values)

Mean Sea Level: 3.523913043478261 inches
Sum of Sea Level Data: 162.1 inches
Combined Data (Years and Original Sea Levels):
[[1.880e+03 1.000e-01]
 [1.881e+03 1.000e-01]
 [1.882e+03 1.000e-01]
 [1.883e+03 1.000e-01]
 [1.884e+03 1.000e-01]
 [1.885e+03 1.000e-01]
 [1.886e+03 1.000e-01]
 [1.887e+03 1.000e-01]
 [1.888e+03 1.000e-01]
 [1.889e+03 1.000e-01]
 [1.890e+03 1.000e-01]
 [1.891e+03 1.000e-01]
 [1.892e+03 1.000e-01]
 [1.893e+03 1.000e-01]
 [1.894e+03 1.000e-01]
 [1.895e+03 1.000e-01]
 [1.896e+03 1.000e-01]
 [1.897e+03 1.000e-01]
 [1.898e+03 1.000e-01]
 [1.899e+03 1.000e-01]
 [1.900e+03 1.000e-01]
 [2.000e+03 4.200e+00]
 [2.001e+03 4.300e+00]
 [2.002e+03 4.500e+00]
 [2.003e+03 4.700e+00]
 [2.004e+03 4.900e+00]
 [2.005e+03 5.000e+00]
 [2.006e+03 5.200e+00]
 [2.007e+03 5.400e+00]
 [2.008e+03 5.600e+00]
 [2.009e+03 5.700e+00]
 [2.010e+03 5.900e+00]
 [2.011e+03 6.100e+00]
 [2.012e+03 6.300e+00]
 [2.013e+03 6.500e+00]
 [2.014e+03 6.700e+00]
 [2.015e+03 6.900e+00]
 [2.016e+03 7.100e+00]
 [

In [5]:
#
import numpy as np
import pandas as pd

data_frame = pd.read_csv('epa-sea-level.csv')

years = data_frame['Year'].values
sea_levels = data_frame['CSIRO Adjusted Sea Level'].values

year_2000_sea_level = sea_levels[years == 2000][0]
sea_level_change = sea_levels - year_2000_sea_level

print("Sea Level Change (Relative to Year 2000):")
print(sea_level_change)

scaling_factor = 0.2
adjusted_sea_levels = sea_levels + scaling_factor * (years - 2000)

print("Adjusted Sea Levels:")
print(adjusted_sea_levels)

years_above_7 = years[sea_levels > 7]
sea_levels_above_7 = sea_levels[sea_levels > 7]

print("Years with Sea Levels Greater Than 7 Inches:")
print(years_above_7)
print(sea_levels_above_7)

combined_data = np.column_stack((years, adjusted_sea_levels))

print("Combined Data (Years and Adjusted Sea Levels):")
print(combined_data)

Sea Level Change (Relative to Year 2000):
[-4.1 -4.1 -4.1 -4.1 -4.1 -4.1 -4.1 -4.1 -4.1 -4.1 -4.1 -4.1 -4.1 -4.1
 -4.1 -4.1 -4.1 -4.1 -4.1 -4.1 -4.1  0.   0.1  0.3  0.5  0.7  0.8  1.
  1.2  1.4  1.5  1.7  1.9  2.1  2.3  2.5  2.7  2.9  3.1  3.3  3.6  3.8
  4.   4.3  4.5  4.8]
Adjusted Sea Levels:
[-23.9 -23.7 -23.5 -23.3 -23.1 -22.9 -22.7 -22.5 -22.3 -22.1 -21.9 -21.7
 -21.5 -21.3 -21.1 -20.9 -20.7 -20.5 -20.3 -20.1 -19.9   4.2   4.5   4.9
   5.3   5.7   6.    6.4   6.8   7.2   7.5   7.9   8.3   8.7   9.1   9.5
   9.9  10.3  10.7  11.1  11.6  12.   12.4  12.9  13.3  13.8]
Years with Sea Levels Greater Than 7 Inches:
[2016 2017 2018 2019 2020 2021 2022 2023 2024]
[7.1 7.3 7.5 7.8 8.  8.2 8.5 8.7 9. ]
Combined Data (Years and Adjusted Sea Levels):
[[1880.   -23.9]
 [1881.   -23.7]
 [1882.   -23.5]
 [1883.   -23.3]
 [1884.   -23.1]
 [1885.   -22.9]
 [1886.   -22.7]
 [1887.   -22.5]
 [1888.   -22.3]
 [1889.   -22.1]
 [1890.   -21.9]
 [1891.   -21.7]
 [1892.   -21.5]
 [1893.   -21.3]
 [1894.